### ISSUE TITLE
Question About Reproducing Baseline Results

### ISSUE THREAD

**Issue by DimitriosGkegkas** [mcederle99/MAD4QN-PS#1]
Thank you for this amazing repository! It's been really useful, and I’ve successfully reproduced the paper's results using the provided models and evaluation scripts, as well as the random policy.

I was wondering if there’s a script or guidance available for reproducing the results of the other baselines mentioned in the paper? Any help would be greatly appreciated.

Thanks again for your great work!

**Comment by mcederle99** [comment]
Thank you for your appreciation! I'm really happy that you found this repo useful, it means a lot to me!

Regarding the other baselines' results, you are right that in this repo you can only find the np.arrays of the performances. This is because I had to run those simulations by using another library that interfaces with SUMO, i.e. Flow (https://github.com/flow-project/flow), because when using SMARTS I was not able to properly use and set the traffic lights.
Anyways, once you have cloned and set up Flow, you will be able to run the baselines by running the file baselines.sh inside the zip folder attached to this message (I should put it in the repo, my bad).
To run the different baselines you have to change a line in the script main_final.py (I've put a comment in the corresponding line), and in the associated .xml file you can choose the cycle length that you prefer for the traffic lights (I think that it's easier to see it in the code than to explain it in words).

An important thing, the first time that you run the code you will probably get an error related to SUMO, something similar to:
_Error: File '/tmp/flow/debug/cfg/map.net.xml' is not accessible (No such file or directory)._
What I did was going inside that folder and manually copy inside it the file map.net.xml (or map_actuated.net.xml). After that the issue was solved.

I hope this explanations is clear and useful, let me know if you have further questions!

[baselines.zip](https://github.com/user-attachments/files/18110510/baselines.zip)

**Comment by DimitriosGkegkas** [comment]
Thank you so much for the detailed description and code—it is really helpful! 🙏

I am going to work on integrating them with SMARTS (still haven’t found a clean solution, but I’ll let you know once I do).

Again, thank you so much for the help. Of course, you can close the issue.

**Comment by mcederle99** [comment]
Thank you! That would be really helpful💪
